[package]
name = "yew-app"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3.85"
# this is the development version of Yew
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }


